name: 'medical_transform'
version: '1.0.0'
config-version: 2

profile: 'medical_transform'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  medical_transform:
    staging:
      +materialized: view
    marts:
      +materialized: table