version: 2

models:
  - name: stg_medical_data
    description: Staging model for raw medical data
    columns:
      - name: message_key
        tests:
          - unique
          - not_null
      - name: message_date
        tests:
          - not_null